### ISSUE TITLE
Mensagem de fechamento forçado e melhorias

### ISSUE THREAD

**Issue by squillace91** [rterrabh/LFApp#11]
Não achei bug grave não, (Android) só quando voce minimiza ele, acessa outro app e vai tentar clicar no icone dele acusa uma mensagem que ele teve de ser fechado e voce tem que apertar Ok... mas ele volta com o que tava antes, então voce nao perde nada.

Sugestoes para o futuro: 

-melhorar usabilidade dos itens (remoções da forma de chomsky)

-manter um historico do que voce ja testou, varias vezes eu quis rever algo e tive que digitar a gramatica novamente

**Comment by roberto-goncalves** [comment]
Engraçado, isso não deu na minha versão do Android. Ele entra e sai normalmente, porém acontece que perde o que foi feito.
