### ISSUE TITLE
Suporte à orientação de tela landscape

### ISSUE THREAD

**Issue by CarlosPereira27** [rterrabh/LFApp#22]
Com a tela em landscape é muito difícil de inserir a gramática. Pois o teclado padrão abre na tela inteira e os botões não ficam disponíveis para o usuário, somente se ele fechar o teclado.
![captura de tela de 2016-07-16 14 40 36](https://cloud.githubusercontent.com/assets/16121305/16902251/2267a5f8-4c30-11e6-9d40-fcaab75ac8b3.png)
![captura de tela de 2016-07-16 14 40 12](https://cloud.githubusercontent.com/assets/16121305/16902252/29cd78cc-4c30-11e6-9826-3c7dd01c76c2.png)
Possível solução: desenvolver um teclado  específico para a aplicação.
![captura de tela de 2016-07-16 14 33 18](https://cloud.githubusercontent.com/assets/16121305/16902255/5c7fdf62-4c30-11e6-9580-34786a26c3c8.png)

**Comment by rterrabh** [comment]
Recomendo, por enquanto, desativar a opção landscape. Como já está assim, fecho esse issue.
