### ISSUE TITLE
Problema na visualização de botões na tela inicial

### ISSUE THREAD

**Issue by CarlosPereira27** [rterrabh/LFApp#24]
O foco do teclado padrão em relação ao texto faz com que em alguns cenários os botões não fiquem visíveis ao usuário.
Exemplo, após 17 linhas da gramática, com o cursor na linha 17.
![captura de tela de 2016-07-17 15 20 53](https://cloud.githubusercontent.com/assets/16121305/16902314/209995d6-4c32-11e6-967a-7a6a7dfe8d45.png)
No mesmo cenário  movendo o cursor para a linha 1.
![captura de tela de 2016-07-17 15 22 15](https://cloud.githubusercontent.com/assets/16121305/16902320/4628f49a-4c32-11e6-9309-d8bfaf02777a.png)

**Comment by rterrabh** [comment]
Recomendo limitar o tamanho do campo no máximo em que os botões de auxílio fiquem visíveis e, logicamente (e talvez automaticamente), seja incluída um barra de rolagem vertical.

**Comment by CarlosPereira27** [comment]
Solução:

Há dois modos de reajuste de tela para inserção do teclado virtual:
- _PAN_ - neste modo é garantido o foco na _view_ onde o texto está sendo inserido, porém a combinação do foco com o _scroll_ desta _view_ pode tirar outras _views_ da tela. O que acontecia com os botões dependendo da posição do _scroll_.
-  _RESIZE_ - neste modo toda a tela é exibida, porém de forma reduzida para a inserção do teclado virtual.

A solução foi utilizar o modo _RESIZE_ combinado com a remoção das _views_ desnecessárias para a definição de uma gramática. Então, quando o usuário entra no modo de edição do texto da gramática, as _views_ da palavra e dos botões histórico e informações são removidas.

![1](https://cloud.githubusercontent.com/assets/16121305/19564025/ed7a056c-96c0-11e6-9e06-f017c28bba4b.png)

![2](https://cloud.githubusercontent.com/assets/16121305/19564131/4096776c-96c1-11e6-8891-bbeb19ceed16.png)

![3](https://cloud.githubusercontent.com/assets/16121305/19564148/495d50e6-96c1-11e6-9932-fa841cc2e95a.png)

![14](https://cloud.githubusercontent.com/assets/16121305/19564156/5200971c-96c1-11e6-97a9-17ef2b8d7584.png)
