### ISSUE TITLE
Somente é possível abrir aplicativo pela Play Store

### ISSUE THREAD

**Issue by CarlosPereira27** [rterrabh/LFApp#26]
Problema referente  ao erro, em que só é possível abrir o LFApp pela PlayStore, por outros meios retorna a mensagem "Unfortunately, LFApp has stopped."
Problema estava presente na última versão do aplicativo na PlayStore.
![captura de tela de 2016-07-27 13-45-37](https://cloud.githubusercontent.com/assets/16121305/17184013/703a3a8e-5400-11e6-803e-6a84c500c541.png)
Stack trace
![captura de tela de 2016-07-27 09-15-15](https://cloud.githubusercontent.com/assets/16121305/17184018/78c56e30-5400-11e6-9603-664ad2d73936.png)
Código 
![captura de tela de 2016-07-27 09-15-39](https://cloud.githubusercontent.com/assets/16121305/17184022/820d5566-5400-11e6-991a-516584c743ea.png)

**Comment by rterrabh** [comment]
Olá Carlos, poderia descrever onde era o problema e qual foi a solução aplicada?

**Comment by CarlosPereira27** [comment]
O problema era um NullPointerException. Ele era lançado, pois nesta versão do código, ao dar um clique na gramática, na _activity_ de saída dos algoritmos, ela retornava para a principal passando a gramática pela _Intent_ usando um _Bundle_. A _activity_ principal apenas verificava se a _Intent_ e o _Bundle_ eram diferentes de _null_. Portanto esperava-se que se o _Bundle_ existisse, ele teria um valor mapeado para a chave "_grammar_". 
Porém quando fecha o LFApp pelo círculo, na barra inferior do Android, e volta pelo ícone do LFApp, ele tenta criar a _activity_ principal, passando um _Bundle_ pela _Intent_ com um mapeamento da chave "profile" para o valor 0. Portanto, nesta situação, o _Intent_ não é diferente de null, o _Bundle_ também não, porém a chave "_grammar_" não existe no _Bundle_. Então o retorno do seu valor é _null_, gerando um NullPointerException e derrubando a aplicação. 
Solução: poderia ser apenas uma verificação se o valor relacionado a chave "_grammar_" é diferente de _null_. Porém este código já não é mais utilizado.
